name: Update Latest Branch

on:
  push:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      versionBumped: ${{ steps.version_check.outputs.versionBumped }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if package.json version bumped
        id: version_check
        run: |
          set -e
          old_version=$(git show HEAD^:package.json | jq -r .version)
          new_version=$(jq -r .version package.json)
          if [ "$old_version" != "$new_version" ]; then
            echo "versionBumped=true" >> $GITHUB_OUTPUT
          else
            echo "versionBumped=false" >> $GITHUB_OUTPUT
          fi

  update-latest:
    needs: check-version
    if: needs.check-version.outputs.versionBumped == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to latest branch
        run: git push -f origin HEAD:latest
